spring:
  application:
    name: appointment_service
  datasource:
    url: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DIALECT}
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

user-service-url: http://user-service:8080
springdoc:
  swagger-ui:
    config-url: /appointments/v3/api-docs/swagger-config
    url: /appointments/v3/api-docs

grpc:
  client:
    user-service:
      address: "static://user-service:9090"
      negotiation-type: plaintext
