spring:
  application:
    name: appointment_service
  datasource:
    url: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DIALECT}
    show-sql: true
  rabbitmq:
    host: ${HOSPITAL_APP_RABBITMQ_HOST}
    port: ${HOSPITAL_APP_RABBITMQ_PORT}
    username: ${HOSPITAL_APP_RABBITMQ_USER}
    password: ${HOSPITAL_APP_RABBITMQ_PASS}
    ssl:
      enabled: ${HOSPITAL_APP_RABBITMQ_SSL_ENABLED}
      algorithm: ${HOSPITAL_APP_RABBITMQ_SSL_ALGO}
      validate-server-certificate: ${HOSPITAL_APP_RABBITMQ_SSL_VALIDATE}
      key-store: ${HOSPITAL_APP_RABBITMQ_KEYSTORE}
      key-store-password: ${HOSPITAL_APP_RABBITMQ_KEYSTORE_PASS}
      trust-store: ${HOSPITAL_APP_RABBITMQ_TRUSTSTORE}
      trust-store-password: ${HOSPITAL_APP_RABBITMQ_TRUSTSTORE_PASS}

user-service-url: ${HOSPITAL_APP_USER_SERVICE_URL}
springdoc:
  swagger-ui:
    config-url: /appointments/v3/api-docs/swagger-config
    url: /appointments/v3/api-docs

grpc:
  client:
    user-service:
      address: static://user-service:9090
      negotiation-type: TLS
      security:
        certificate-chain: ${HOSPITAL_APP_APPOINTMENT_SERVICE_CRT}
        private-key: ${HOSPITAL_APP_APPOINTMENT_SERVICE_KEY}
        trust-cert-collection: ${HOSPITAL_APP_APPOINTMENT_SERVICE_CA}
